name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
      - name: Build server and loadgen (linux/amd64)
        run: |
          set -euo pipefail
          mkdir -p dist
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s -w" -o dist/llm-router-linux-amd64 ./cmd/server
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s -w" -o dist/loadgen-linux-amd64 ./cmd/loadgen
          tar -czf dist/llm-router-linux-amd64.tar.gz -C dist llm-router-linux-amd64 README.md || true
          tar -czf dist/loadgen-linux-amd64.tar.gz -C dist loadgen-linux-amd64 README.md || true
      - name: Build server and loadgen (linux/arm64)
        run: |
          set -euo pipefail
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags "-s -w" -o dist/llm-router-linux-arm64 ./cmd/server
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags "-s -w" -o dist/loadgen-linux-arm64 ./cmd/loadgen
          tar -czf dist/llm-router-linux-arm64.tar.gz -C dist llm-router-linux-arm64 README.md || true
          tar -czf dist/loadgen-linux-arm64.tar.gz -C dist loadgen-linux-arm64 README.md || true
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/llm-router:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/llm-router:latest
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            dist/llm-router-linux-amd64.tar.gz
            dist/llm-router-linux-arm64.tar.gz
            dist/loadgen-linux-amd64.tar.gz
            dist/loadgen-linux-arm64.tar.gz
